// Mocks generated by Mockito 5.4.6 from annotations
// in luar_sekolah_lms/test/week11/unit/controllers/item_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:luar_sekolah_lms/week11/domain/entities/item.dart' as _i3;
import 'package:luar_sekolah_lms/week11/domain/repositories/item_repository.dart'
    as _i2;
import 'package:luar_sekolah_lms/week11/domain/usecases/create_item_usecase.dart'
    as _i6;
import 'package:luar_sekolah_lms/week11/domain/usecases/delete_item_usecase.dart'
    as _i8;
import 'package:luar_sekolah_lms/week11/domain/usecases/get_items_usecase.dart'
    as _i4;
import 'package:luar_sekolah_lms/week11/domain/usecases/update_item_usecase.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeItemRepository_0 extends _i1.SmartFake
    implements _i2.ItemRepository {
  _FakeItemRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeItem_1 extends _i1.SmartFake implements _i3.Item {
  _FakeItem_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetItemsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetItemsUseCase extends _i1.Mock implements _i4.GetItemsUseCase {
  MockGetItemsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ItemRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeItemRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ItemRepository);

  @override
  _i5.Future<List<_i3.Item>> call({int? page = 0, int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#page: page, #limit: limit}),
            returnValue: _i5.Future<List<_i3.Item>>.value(<_i3.Item>[]),
          )
          as _i5.Future<List<_i3.Item>>);
}

/// A class which mocks [CreateItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateItemUseCase extends _i1.Mock implements _i6.CreateItemUseCase {
  MockCreateItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ItemRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeItemRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ItemRepository);

  @override
  _i5.Future<_i3.Item> call(String? title, String? description) =>
      (super.noSuchMethod(
            Invocation.method(#call, [title, description]),
            returnValue: _i5.Future<_i3.Item>.value(
              _FakeItem_1(this, Invocation.method(#call, [title, description])),
            ),
          )
          as _i5.Future<_i3.Item>);
}

/// A class which mocks [UpdateItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateItemUseCase extends _i1.Mock implements _i7.UpdateItemUseCase {
  MockUpdateItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ItemRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeItemRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ItemRepository);

  @override
  _i5.Future<_i3.Item> call(_i3.Item? item) =>
      (super.noSuchMethod(
            Invocation.method(#call, [item]),
            returnValue: _i5.Future<_i3.Item>.value(
              _FakeItem_1(this, Invocation.method(#call, [item])),
            ),
          )
          as _i5.Future<_i3.Item>);
}

/// A class which mocks [DeleteItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteItemUseCase extends _i1.Mock implements _i8.DeleteItemUseCase {
  MockDeleteItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ItemRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeItemRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ItemRepository);

  @override
  _i5.Future<void> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
