// Mocks generated by Mockito 5.4.6 from annotations
// in luar_sekolah_lms/test/week11/unit/usecases/get_items_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:luar_sekolah_lms/week11/domain/entities/item.dart' as _i2;
import 'package:luar_sekolah_lms/week11/domain/repositories/item_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeItem_0 extends _i1.SmartFake implements _i2.Item {
  _FakeItem_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ItemRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemRepository extends _i1.Mock implements _i3.ItemRepository {
  MockItemRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Item>> getItems({int? page = 0, int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getItems, [], {#page: page, #limit: limit}),
            returnValue: _i4.Future<List<_i2.Item>>.value(<_i2.Item>[]),
          )
          as _i4.Future<List<_i2.Item>>);

  @override
  _i4.Future<_i2.Item> createItem(String? title, String? description) =>
      (super.noSuchMethod(
            Invocation.method(#createItem, [title, description]),
            returnValue: _i4.Future<_i2.Item>.value(
              _FakeItem_0(
                this,
                Invocation.method(#createItem, [title, description]),
              ),
            ),
          )
          as _i4.Future<_i2.Item>);

  @override
  _i4.Future<_i2.Item> updateItem(_i2.Item? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, [item]),
            returnValue: _i4.Future<_i2.Item>.value(
              _FakeItem_0(this, Invocation.method(#updateItem, [item])),
            ),
          )
          as _i4.Future<_i2.Item>);

  @override
  _i4.Future<void> deleteItem(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteItem, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
